import{initializeApp,getApp,getApps}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import{getDatabase,ref,onValue,get}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";

const config={apiKey:"AIzaSyCMwXWSbbFRTHcKx9nixhAg7hHvk-6yr-Y",authDomain:"earnbdwork.firebaseapp.com",databaseURL:"https://earnbdwork-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"earnbdwork",storageBucket:"earnbdwork.firebasestorage.app",messagingSenderId:"463458443517",appId:"1:463458443517:web:ed7e89c1ccb6eee3075e94"};
const app=getApps().length?getApp():initializeApp(config),db=getDatabase(app),auth=getAuth(app),isHome=/\/(index\.html)?$/i.test(location.pathname)||location.pathname==="/";
const defaults={brandName:"SHAKIL m game",liveLabel:"LIVE • SHAKIL m game",heroTitle:"SHAKIL m game — লুডো, ২৯ কার্ড এবং আরও গেম",heroSubtitle:"যে গেমটি খেলতে চান সেটি বেছে নিন।",announcement:"",footerName:"SHAKIL m game",maintenance:false,showShop:true,showLeaderboard:true,theme:{primary:"#ffc93c",secondary:"#7c3aed",background:"#0b0620",card:"#241758",board:"#122145",glow:"#6d83ff",radius:22}};
let latest={settings:defaults,rawSettings:{},games:{},hasRemoteSettings:false};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function themeStyle(t){let el=document.getElementById("admin-runtime-theme");if(!el){el=document.createElement("style");el.id="admin-runtime-theme";document.head.appendChild(el)}const p=t.primary||defaults.theme.primary,s=t.secondary||defaults.theme.secondary,bg=t.background||defaults.theme.background,g=t.glow||defaults.theme.glow,r=Number(t.radius)||22;el.textContent=`:root{--admin-primary:${p};--admin-secondary:${s};--admin-bg:${bg};--admin-glow:${g};--admin-radius:${r}px}body{--admin-theme-glow:${g}}`}
function announcement(s){let el=document.getElementById("admin-runtime-announcement");if(!s.announcement){el?.remove();return}if(!el){el=document.createElement("div");el.id="admin-runtime-announcement";el.style.cssText="position:relative;z-index:50;width:min(1120px,calc(100% - 28px));margin:14px auto 0;padding:11px 15px;font:800 12px/1.5 system-ui;text-align:center;border-radius:14px";(document.querySelector("main")||document.body).prepend(el)}el.textContent="📢 "+s.announcement}
function maintenance(s){let el=document.getElementById("admin-runtime-maintenance");if(!s.maintenance){el?.remove();return}if(!el){el=document.createElement("div");el.id="admin-runtime-maintenance";el.style.cssText="position:fixed;inset:0;z-index:99999;display:grid;place-items:center;padding:22px;text-align:center;font:600 14px/1.65 system-ui;background:#080312ee;color:#fff";el.innerHTML='<div style="max-width:430px;padding:30px;border:1px solid #ffffff22;border-radius:24px;background:#111021ee;box-shadow:0 24px 80px #000b"><div style="font-size:44px">🛠️</div><h2 style="margin:10px 0 5px">সাইট আপডেট চলছে</h2><p style="margin:0;color:#c9d2e5">আমরা নতুন game ও feature যোগ করছি। কিছুক্ষণ পরে আবার চেষ্টা করুন।</p></div>';document.body.appendChild(el)}}
function applySettings(raw,remote=false){if(remote){latest.hasRemoteSettings=true;latest.rawSettings=raw||{}}if(!latest.hasRemoteSettings)return;const s=Object.assign({},defaults,latest.rawSettings||{},{theme:Object.assign({},defaults.theme,(latest.rawSettings||{}).theme||{})});latest.settings=s;themeStyle(s.theme);if(typeof window.__applyAdminSettings==="function")window.__applyAdminSettings(s);if(isHome){announcement(s);maintenance(s)}}
function applyGames(raw){latest.games=raw||{};if(typeof window.__applyAdminGames==="function")window.__applyAdminGames(latest.games)}
function injectAdminLink(user){get(ref(db,"admins/"+user.uid)).then(s=>{if(s.val()!==true||document.getElementById("admin-runtime-link"))return;const a=document.createElement("a");a.id="admin-runtime-link";a.href="admin-panel.html";a.textContent="⚙️ Admin";a.style.cssText="position:fixed;right:16px;bottom:16px;z-index:9000;padding:9px 12px;border:1px solid #ffd76d55;border-radius:999px;background:#101321ed;color:#ffe49b;text-decoration:none;font:900 11px system-ui;box-shadow:0 8px 22px #0008";document.body.appendChild(a)}).catch(()=>{})}
onValue(ref(db,"siteSettings"),s=>applySettings(s.val()||{},s.exists()),()=>{});
onValue(ref(db,"games"),s=>applyGames(s.val()||{}),()=>{});
onAuthStateChanged(auth,u=>{if(u)injectAdminLink(u)});
