import{initializeApp,getApp,getApps}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import{getDatabase,ref,onValue,get}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";

const config={apiKey:"AIzaSyCMwXWSbbFRTHcKx9nixhAg7hHvk-6yr-Y",authDomain:"earnbdwork.firebaseapp.com",databaseURL:"https://earnbdwork-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"earnbdwork",storageBucket:"earnbdwork.firebasestorage.app",messagingSenderId:"463458443517",appId:"1:463458443517:web:ed7e89c1ccb6eee3075e94"};
const app=getApps().length?getApp():initializeApp(config),db=getDatabase(app),auth=getAuth(app),home=/\/((index|soverix-net-homepage-final)\.html)?$/i.test(location.pathname)||location.pathname==="/",esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;",'\'':"&#39;"}[c]));
const defaults={brandName:"Soverix Net",liveLabel:"LIVE • BANGLADESH #1",heroTitle:"Bangladesh's No.1 - Ludo + 29 Card - 3D + Betting + Shop",heroSubtitle:"খেলুন, practice করুন এবং virtual rewards সংগ্রহ করুন — demo mode only।",announcement:"",footerName:"Soverix Net 2026",maintenance:false,showShop:true,showLeaderboard:true,theme:{primary:"#ffd76d",secondary:"#7c3aed",background:"#070810",card:"#111321",board:"#122145",glow:"#6d83ff",radius:18}};
let latest={settings:defaults,games:{},hasRemoteSettings:false};let scheduled=0;
function schedule(){if(scheduled)return;scheduled=1;requestAnimationFrame(()=>{scheduled=0;applyAll()})}
function themeStyle(t){let s=document.getElementById("admin-runtime-theme");if(!s){s=document.createElement("style");s.id="admin-runtime-theme";document.head.appendChild(s)}const primary=t.primary||defaults.theme.primary,secondary=t.secondary||defaults.theme.secondary,bg=t.background||defaults.theme.background,card=t.card||defaults.theme.card,board=t.board||defaults.theme.board,glow=t.glow||defaults.theme.glow,r=Number(t.radius)||18;s.textContent=`:root{--admin-primary:${primary};--admin-secondary:${secondary};--admin-bg:${bg};--admin-card:${card};--admin-board:${board};--admin-glow:${glow};--admin-radius:${r}px}#admin-runtime-announcement{background:linear-gradient(110deg,${primary}20,${secondary}22);border:1px solid ${primary}55;color:#fff2bd;border-radius:${Math.min(r,24)}px;box-shadow:0 10px 30px ${glow}25}#admin-runtime-maintenance{background:radial-gradient(circle at 50% 0,${secondary}66,${bg}f5 65%);color:#fff}body{--admin-theme-glow:${glow}}${home?`body{background-color:${bg}}button[data-admin-game]{border-color:${primary}55!important;box-shadow:0 6px 0 ${secondary}66,0 10px 28px ${glow}22!important}`:`canvas{box-shadow:0 8px 26px ${glow}55!important}`}`}
function applySettings(raw,remote=false){if(remote)latest.hasRemoteSettings=true;if(!latest.hasRemoteSettings)return;const s=Object.assign({},defaults,raw||{}, {theme:Object.assign({},defaults.theme,raw?.theme||{})});latest.settings=s;themeStyle(s.theme);if(home){const headings=[...document.querySelectorAll("h1")],brand=headings.find(x=>/Soverix Net/i.test(x.textContent||""));if(brand&&s.brandName)brand.textContent=s.brandName;const live=[...document.querySelectorAll("body *")].find(x=>x.children.length===0&&/LIVE • BANGLADESH #1/i.test(x.textContent||""));if(live&&s.liveLabel)live.textContent=s.liveLabel;const hero=[...document.querySelectorAll("body *")].find(x=>x.children.length===0&&/Bangladesh's No\.1/i.test(x.textContent||""));if(hero&&s.heroTitle)hero.textContent=s.heroTitle;const subtitle=[...document.querySelectorAll("body *")].find(x=>x.children.length===0&&/Classic Ludo with modern 3D engine/i.test(x.textContent||""));if(subtitle&&s.heroSubtitle)subtitle.textContent=s.heroSubtitle;const footer=[...document.querySelectorAll("body *")].find(x=>x.children.length===0&&/Soverix Net 2026/i.test(x.textContent||""));if(footer&&s.footerName)footer.textContent=s.footerName;const shop=[...document.querySelectorAll("button")].find(b=>b.textContent.trim()==="Shop");if(shop)shop.style.display=s.showShop===false?"none":"";const lb=document.getElementById("earn-home-lb");if(lb)lb.style.display=s.showLeaderboard===false?"none":"";renderAnnouncement(s);renderMaintenance(s)}schedule()}
function renderAnnouncement(s){let el=document.getElementById("admin-runtime-announcement");if(!s.announcement){el?.remove();return}if(!el){el=document.createElement("div");el.id="admin-runtime-announcement";el.style.cssText="position:relative;z-index:50;width:min(1120px,calc(100% - 28px));margin:14px auto 0;padding:11px 15px;font:800 12px/1.5 system-ui;text-align:center";const main=document.querySelector("main")||document.body;main.prepend(el)}el.textContent="📢 "+s.announcement}
function renderMaintenance(s){let el=document.getElementById("admin-runtime-maintenance");if(!s.maintenance){el?.remove();return}if(!el){el=document.createElement("div");el.id="admin-runtime-maintenance";el.style.cssText="position:fixed;inset:0;z-index:99999;display:grid;place-items:center;padding:22px;text-align:center;font:600 14px/1.65 system-ui";el.innerHTML='<div style="max-width:430px;padding:30px;border:1px solid #ffffff22;border-radius:24px;background:#080a12cc;box-shadow:0 24px 80px #000b"><div style="font-size:44px">🛠️</div><h2 style="margin:10px 0 5px">সাইট আপডেট চলছে</h2><p style="margin:0;color:#c9d2e5">আমরা নতুন game ও feature যোগ করছি। কিছুক্ষণ পরে আবার চেষ্টা করুন।</p></div>';document.body.appendChild(el)}}
function findHeading(needle){return[...document.querySelectorAll("h1,h2,h3,h4")].find(x=>(x.textContent||"").toLowerCase().includes(needle.toLowerCase()))}
function findCard(heading){return heading?.closest(".group")||heading?.parentElement?.parentElement||null}
function setGameCard(id,g){const h=findHeading(id==="ludo"?"Soverix Ludo":id==="card29"?"Soverix 29":"SHAKIL");if(!h)return;const card=findCard(h);if(card){card.style.display=g.visible===false?"none":"";const title=card.querySelector("h3,h2,h4");if(title)title.textContent=g.title||title.textContent;const ps=[...card.querySelectorAll("p")];const desc=ps.find(p=>/engine|authentic|updated|ludo|card/i.test(p.textContent||""));if(desc&&g.subtitle)desc.textContent=g.subtitle}const buttons=card?[...card.querySelectorAll("button")]:[];const play=buttons.find(b=>/Play Now|SHAKIL|আধুনিক গেমস|Play Modern/i.test(b.textContent||""));if(play){play.textContent=(g.icon?g.icon+" ":"")+(g.buttonLabel||"Play");play.dataset.adminGame=id;play.style.display=g.visible===false?"none":"";play.style.background=`linear-gradient(135deg,${g.accent||defaults.theme.primary},${latest.settings.theme.secondary})`;if(!play.dataset.adminBound){play.addEventListener("click",()=>{if(g.route)location.href=g.route});play.dataset.adminBound="1"}}}
function renderCustomGames(games){const custom=Object.entries(games).filter(([id,g])=>!['ludo','shakil','card29'].includes(id)&&g&&g.visible!==false);let host=document.getElementById("admin-custom-games");if(!custom.length){host?.remove();return}if(!host){host=document.createElement("section");host.id="admin-custom-games";host.style.cssText="width:min(1120px,calc(100% - 28px));margin:22px auto;display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px";const footer=document.querySelector("footer");(footer?.parentElement||document.body).insertBefore(host,footer||null)}host.innerHTML=custom.map(([id,g])=>`<article style="padding:18px;border-radius:18px;border:1px solid ${(g.accent||defaults.theme.primary)}66;background:linear-gradient(145deg,${g.accent||defaults.theme.secondary}20,#111321ee);box-shadow:0 14px 35px #0005"><div style="font-size:27px">${esc(g.icon||"🎮")}</div><h3 style="margin:8px 0 3px;font-size:16px">${esc(g.title||id)}</h3><p style="margin:0;color:#aeb9ce;font-size:11px;line-height:1.5">${esc(g.subtitle||"")}</p><button data-admin-game="${esc(id)}" style="width:100%;margin-top:13px;border:1px solid #ffffff22;border-radius:10px;padding:10px;color:#fff;background:${esc(g.accent||defaults.theme.secondary)};font-weight:900">${esc(g.buttonLabel||"Play")}</button></article>`).join("");host.querySelectorAll("button[data-admin-game]").forEach((b,i)=>{const g=custom[i][1];b.addEventListener("click",()=>g.route&&(location.href=g.route))})}
function applyGames(raw){latest.games=raw||{};if(!home){schedule();return}const games=raw||{};if(games.ludo)setGameCard("ludo",games.ludo);if(games.shakil){const all=[...document.querySelectorAll("button")],b=all.find(x=>/আধুনিক গেমস|SHAKIL Ludo King|Play Modern Games/i.test(x.textContent||""));if(b){b.textContent=(games.shakil.icon?games.shakil.icon+" ":"")+games.shakil.buttonLabel;b.style.display=games.shakil.visible===false?"none":"";b.dataset.adminGame="shakil";if(!b.dataset.adminBound){b.addEventListener("click",()=>games.shakil.route&&(location.href=games.shakil.route));b.dataset.adminBound="1"}}}if(games.card29)setGameCard("card29",games.card29);renderCustomGames(games);schedule()}
function applyAll(){applySettings(latest.settings,latest.hasRemoteSettings);applyGames(latest.games)}
function injectAdminLink(user){get(ref(db,"admins/"+user.uid)).then(s=>{if(s.val()!==true)return;if(document.getElementById("admin-runtime-link"))return;const a=document.createElement("a");a.id="admin-runtime-link";a.href="admin-panel.html";a.textContent="⚙️ Admin";a.style.cssText="position:fixed;right:16px;bottom:16px;z-index:9000;padding:9px 12px;border:1px solid #ffd76d55;border-radius:999px;background:#101321ed;color:#ffe49b;text-decoration:none;font:900 11px system-ui;box-shadow:0 8px 22px #0008";document.body.appendChild(a)})}
onValue(ref(db,"siteSettings"),s=>applySettings(s.val()||{},!!s.val()),()=>{});onValue(ref(db,"games"),s=>applyGames(s.val()||{}),()=>{});onAuthStateChanged(auth,u=>{if(u)injectAdminLink(u)});setTimeout(applyAll,1200);
